version: '3.8'
services:
  sql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: ji8lae0aequai!hee3In
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-network


  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  postgres_data: